# Generated by Django 3.2.18 on 2023-03-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountbooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbook',
            old_name='title',
            new_name='note',
        ),
    ]
